import { AchievementBadge } from './types';

export const CANONICAL_ACHIEVEMENTS: AchievementBadge[] = [
  {
    id: 'CENTURION_100K_RIDE',
    name: 'Centurion 100K Century',
    description: 'Complete a single verified cycling ride of 100 kilometers or greater.',
    category: 'DISTANCE',
    tier: 'CENTURION',
    badgeIcon: 'century_gold_shield',
    sport: 'CYCLING',
    scope: 'SINGLE_ACTIVITY',
    threshold: 100000,
    unit: 'meters',
    minEvidenceRequired: 'GPS_VALIDATED',
    version: '1.0',
    status: 'LOCKED',
    unlocked: false
  },
  {
    id: 'MARATHON_HERO',
    name: 'Marathon Hero',
    description: 'Complete a single verified run of 42.195 kilometers (Official Marathon Distance).',
    category: 'DISTANCE',
    tier: 'CENTURION',
    badgeIcon: 'marathon_wreath',
    sport: 'RUNNING',
    scope: 'SINGLE_ACTIVITY',
    threshold: 42195,
    unit: 'meters',
    minEvidenceRequired: 'GPS_VALIDATED',
    version: '1.0',
    status: 'LOCKED',
    unlocked: false
  },
  {
    id: 'HALF_MARATHON_WARRIOR',
    name: 'Half Marathon Warrior',
    description: 'Complete a single verified run of 21.0975 kilometers.',
    category: 'DISTANCE',
    tier: 'GOLD',
    badgeIcon: 'half_marathon_shield',
    sport: 'RUNNING',
    scope: 'SINGLE_ACTIVITY',
    threshold: 21097.5,
    unit: 'meters',
    minEvidenceRequired: 'GPS_VALIDATED',
    version: '1.0',
    status: 'LOCKED',
    unlocked: false
  },
  {
    id: 'SUB_20_5K',
    name: 'Sub-20 5K Lightning',
    description: 'Complete a 5K effort in under 20:00 elapsed time (average pace < 4:00/km).',
    category: 'PACE',
    tier: 'GOLD',
    badgeIcon: 'lightning_bolt_gold',
    sport: 'RUNNING',
    scope: 'SINGLE_ACTIVITY',
    threshold: 1200,
    unit: 'seconds',
    minEvidenceRequired: 'GPS_VALIDATED',
    version: '1.0',
    status: 'LOCKED',
    unlocked: false
  },
  {
    id: 'SUB_45_10K',
    name: 'Sub-45 10K Velocity',
    description: 'Complete a 10K effort in under 45:00 elapsed time.',
    category: 'PACE',
    tier: 'GOLD',
    badgeIcon: 'velocity_star',
    sport: 'RUNNING',
    scope: 'SINGLE_ACTIVITY',
    threshold: 2700,
    unit: 'seconds',
    minEvidenceRequired: 'GPS_VALIDATED',
    version: '1.0',
    status: 'LOCKED',
    unlocked: false
  },
  {
    id: 'EVERESTING_8848_SINGLE_ACTIVITY',
    name: 'Everesting Hero (Single Workout)',
    description: 'Climb 8,848 meters of elevation gain in a single monumental activity.',
    category: 'ELEVATION',
    tier: 'CENTURION',
    badgeIcon: 'mountain_everest_gold',
    scope: 'SINGLE_ACTIVITY',
    threshold: 8848,
    unit: 'meters',
    minEvidenceRequired: 'GPS_VALIDATED',
    version: '1.0',
    status: 'LOCKED',
    unlocked: false
  },
  {
    id: 'ELEVATION_8848_LIFETIME',
    name: 'Everesting Cumulative Pioneer',
    description: 'Climb a cumulative total of 8,848 meters of elevation across all workouts.',
    category: 'ELEVATION',
    tier: 'GOLD',
    badgeIcon: 'mountain_everest_silver',
    scope: 'LIFETIME',
    threshold: 8848,
    unit: 'meters',
    minEvidenceRequired: 'MANUAL',
    version: '1.0',
    status: 'LOCKED',
    unlocked: false
  },
  {
    id: 'DAWN_PATROL',
    name: 'Dawn Patrol',
    description: 'Record and complete a verified workout before 6:00 AM local time.',
    category: 'TIME_OF_DAY',
    tier: 'BRONZE',
    badgeIcon: 'sunrise_shield',
    scope: 'SINGLE_ACTIVITY',
    threshold: 6,
    unit: 'hours',
    minEvidenceRequired: 'GPS_VALIDATED',
    version: '1.0',
    status: 'LOCKED',
    unlocked: false
  },
  {
    id: 'MIDNIGHT_RUNNER',
    name: 'Midnight Runner',
    description: 'Record and complete a workout in the cross-midnight window (10:00 PM to 4:00 AM local time).',
    category: 'TIME_OF_DAY',
    tier: 'SILVER',
    badgeIcon: 'crescent_moon',
    scope: 'SINGLE_ACTIVITY',
    threshold: 0,
    unit: 'hours',
    minEvidenceRequired: 'GPS_VALIDATED',
    version: '1.0',
    status: 'LOCKED',
    unlocked: false
  },
  {
    id: 'STREAK_7_DAYS',
    name: '7-Day Unstoppable Streak',
    description: 'Record a verified activity for 7 consecutive calendar days.',
    category: 'CONSISTENCY',
    tier: 'SILVER',
    badgeIcon: 'streak_flame_silver',
    scope: 'STREAK',
    threshold: 7,
    unit: 'days',
    minEvidenceRequired: 'GPS_VALIDATED',
    version: '1.0',
    status: 'LOCKED',
    unlocked: false
  },
  {
    id: 'STREAK_30_DAYS',
    name: '30-Day Centurion Streak',
    description: 'Record a verified activity for 30 consecutive calendar days.',
    category: 'CONSISTENCY',
    tier: 'CENTURION',
    badgeIcon: 'streak_flame_centurion',
    scope: 'STREAK',
    threshold: 30,
    unit: 'days',
    minEvidenceRequired: 'GPS_VALIDATED',
    version: '1.0',
    status: 'LOCKED',
    unlocked: false
  },
  {
    id: 'CENTURY_CLUB_100_ACTIVITIES',
    name: 'Century Club (100 Workouts)',
    description: 'Log 100 total verified completed activities in RAFTAR.',
    category: 'LIFETIME',
    tier: 'CENTURION',
    badgeIcon: 'centurion_helmet',
    scope: 'LIFETIME',
    threshold: 100,
    unit: 'workouts',
    minEvidenceRequired: 'MANUAL',
    version: '1.0',
    status: 'LOCKED',
    unlocked: false
  }
];
